### ISSUE TITLE
A fix for : evaluate_test_set_predictions.py

### ISSUE THREAD

**Issue by billpku** [craic/bert_paper_classification#1]
Hi, 
Thank you for you wonderful repo, follow with your README, I can run Bert for text classification  perfectly.
In evaluate test data phase, I also use the script **evaluate_test_set_predictions.py** that you supply to evaluate my model with new test data.
In the process, I found that if your **test_original.tsv** has no header which is same format of **train.tsv**. 
Code in **evaluate_test_set_predictions.py** line:36 'i=0' need to set to 'i=1', so that when reading the file , you will not miss the first row.
All in all ,thank you for your nice tutorial.

**Comment by craic** [comment]
Thanks for spotting this - glad you liked the tutorial
